FROM postgres:14

# Install OpenSSL, sudo, and pgvector build dependencies
RUN apt-get update && apt-get install -y openssl sudo build-essential git postgresql-server-dev-14

# Install pgvector
RUN git clone --branch v0.7.2 https://github.com/pgvector/pgvector.git /pgvector
WORKDIR /pgvector
RUN make && make install
WORKDIR /

# Add init scripts while setting permissions
COPY --chmod=755 init-ssl.sh /docker-entrypoint-initdb.d/init-ssl.sh
COPY --chmod=755 init-pgvector.sh /docker-entrypoint-initdb.d/init-pgvector.sh
COPY --chmod=755 wrapper.sh /usr/local/bin/wrapper.sh

ENTRYPOINT ["wrapper.sh"]
CMD ["postgres", "--port=5432"]